#!/bin/bash
#===============================================================================
#
#          FILE: Git Deploy
#
#         USAGE: ./deploy.sh 
#
#   DESCRIPTION: Git Powered Deployment in a script
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Cameron Drake, cameron@drake.fm
#  ORGANIZATION: Ohm Labs
#       CREATED: 06/01/2014 00:24
#      REVISION: ---
#===============================================================================
readonly ScriptVersion="0.1"
readonly PROGDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
readonly HOMEDIR=$(echo $HOME)
readonly PROGNAME=$(basename $0)
readonly ARGS="$@"
readonly GITDIR=/home/git
readonly NGINX_DIR=/etc/nginx
readonly g=/usr/bin/git
# the first thing after deploy will be the name of the service TODO: make mandatory
readonly service_name=$1

[[ $# -eq 0 ]] && {
  # no arguments
  echo echo "Usage: PROGNAME your_repo {u|user|r|repo|b|branch|n|name|v|version}"
  exit 1
}

cmdLine() {
  # while getopts u:r:b:n:v opt
  # do
  #   case "${opt}"
  #   in
  #     -u|--user    ) username=${OPTARG};;
  #     -r|--repo    ) repository=${OPTARG};;
  #     -b|--branch  ) branch=${OPTARG};;
  #     -n|--name    ) service_name=${OPTARG};;
  #     -v|--version ) echo "$0 -- Version $ScriptVersion"; exit 0   ;;
  #                 *) ;;
  #   esac
  # done
  local repository=$service_name
  local username=$2
  local branch=$3
  local git=$GITDIR/$service_name.git
  local work_tree=$GITDIR/public/$service_name
  local scripts_dir=$PROGDIR/$service_name
  echo "Working tree will be: $work_tree on branch $branch"
  echo "Installing service $service_name, a git deployment for: github.com/"$username/$repository
  echo "Sripts and Hooks are in: "$scripts_dir
  echo "Git Directory: $git"
  sudo mkdir -p $git && cd $git
  $g --bare init
  read -p "Deploy key? [Y/N] (visit: https://github.com/$username/$repository/settings/keys)" -n 1
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    $g --bare fetch git@github.com:$username/$repository.git $branch:$branch
    setUp
  elif [[ $REPLY =~ ^[Nn]$ ]]; then
    echo "Proceeding with HTTPS authentication... not advised"
    $g --bare fetch https://github.com/$username/$repository.git $branch:$branch
    setUp
  fi
}
function setUp() {
  sudo cp -i $scripts_dir/hooks/pre-receive.sh $git/hooks/pre-receive
  sudo cp -i $scripts_dir/hooks/post-receive.sh $git/hooks/post-receive
  sudo chmod +x $git/hooks/pre-receive
  sudo chmod +x $git/hooks/post-receive
  sudo cp -i $scripts_dir/service.sh /etc/init.d/$service_name
  sudo chmod 0755 /etc/init.d/$service_name
  sudo mkdir -p $work_tree
  # Backup existing configs
  sudo mv $NGINX_DIR/sites-enabled $NGINX_DIR/sites-enabled.backup
  sudo mkdir -p $NGINX_DIR/sites-enabled
  # Copy new nginx.config  and site-available
  sudo cp -i $scripts_dir/sites-available/* $NGINX_DIR/sites-enabled
}
function main() {
  cmdLine $ARGS
}
main
unset cmdLine
unset setUp
unset main