#!/bin/bash
readonly ScriptVersion="0.2"
readonly PROGDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
readonly PROGNAME=$(basename $0)
readonly ARGS="$@"

[[ $# -eq 0 ]] && {
    # no arguments
    echo "       __           __  
  ____/ /___  _____/ /__
 / __  / __ \/ ___/ //_/
/ /_/ / /_/ / /__/ ,<   
\__,_/\____/\___/_/|_|  
                        "
    echo "Usage: ./$PROGNAME {deploy|prod|loc|version|micro|s3}"
    exit 1;
}
function deploy(){
    $PROGDIR/lib/bin/deploy $2 $3 $4
}
function prodInstall(){
    $PROGDIR/lib/bin/prod
}
function devInstall() {
    $PROGDIR/lib/bin/dev
}
function launchMicro() {
    $PROGDIR/lib/bin/micro
}
function syncS3() {
    $PROGDIR/lib/bin/s3
}
case "$1" in
    -p|--prod|prod    )     prodInstall ;;
    -d|--deploy|deploy )     deploy $ARGS ;;
    -l|--local|loc    )     devInstall $ARGS ;;
    -m|--micro|micro  )     launchMicro $ARGS ;;
    -s|--s3|s3        )     syncS3 $ARGS ;;
    -v|--version      )
        echo "Dependencies Versions:"
        nginx -v
        unzip -v
        node --version
        ruby --version
        mosh --version
        tig --version
        htop --version
        tree --version
        emacs --version
        git --version
        ntpd --version
        bundle show
        npm ls -g --depth=0
        varnishlog
        exit 1;
        ;;
esac
unset prodInstall
unset devInstall
unset launchMicro
unset deploy
unset syncS3
exit 0
